import '../style/modern-normalise.css'
import '../style/style.css'
import '../style/Components/header.css'
import '../style/Components/hero.css'
import '../style/Components/about.css'
import '../style/utils.css'